### ISSUE TITLE
High bandwidth usage

### ISSUE THREAD

**Issue by sudhanshugairola** [bcc-code/bccm-player#16]
When we are playing a video that continuously consuming high bandwidth data again and again after 1 or 2 seconds. Thats bad for a person whose watching video for a short time and he lost half of internet data.

@andreasgangso

**Comment by andreasgangso** [comment]
In general, you should open 1 issue per bug otherwise it can get messy.
I split the network issue into a separate issue: #18

**Comment by andreasgangso** [comment]
I don't understand what you mean here. Can you explain it in more detail?
Any reproduction steps?

**Comment by sudhanshugairola** [comment]
High bandwidth usage

**Comment by sudhanshugairola** [comment]
This means continues data consuming, may be limited my buffering

**Comment by andreasgangso** [comment]
Still don't understand what you mean, your explanations are too short and broad

**Comment by sudhanshugairola** [comment]
Check once YouTube buffering that take less internet data. As compared with bcc_player

**Comment by andreasgangso** [comment]
Then it's likely solved by implementing #2, and possibly adding some better defaults.
Thanks
