### ISSUE TITLE
Internal Storage assets playback issues.

### ISSUE THREAD

**Issue by sudhanshugairola** [bcc-code/bccm-player#21]
Issues with both mkv/mp4 and hls while playing offline file content.

Test with `VideoPlayerView(
                useNativeControls: false,
                controller: controller,
                useSurfaceView: true
   ),`
Following issues are:-

1. Play and Pause button not working.
2. controller.seek(+10 & -10).
3. gettracks like subtitle and audio not showing list in hls content.
4. Seek bar not working.

**Comment by andreasgangso** [comment]
What do you mean by "offline file contents"?

**Comment by sudhanshugairola** [comment]
This means those media files(mp4 or hls) which are in internal storage or phone storage,

**Comment by sudhanshugairola** [comment]
[priority:high]

**Comment by sudhanshugairola** [comment]
ok i will send code

**Comment by sudhanshugairola** [comment]
`controller = BccmPlayerController(
      MediaItem(
        url: '/storage/emulated/0/master480.m3u8',
        mimeType: 'application/x-mpegURL',
        metadata: MediaMetadata(title: 'TEST'),
      ),
    );`

**Comment by sudhanshugairola** [comment]
controller = BccmPlayerController(
      MediaItem(
        url: '/storage/emulated/0/Download/test.mp4',
        mimeType: 'application/x-mpegURL',
        metadata: MediaMetadata(title: 'TEST'),
      ),
    );

**Comment by andreasgangso** [comment]
Let's use #30 to track this as it's the same thing
