### ISSUE TITLE
Feature: Pinch to zoom

### ISSUE THREAD

**Issue by sudhanshugairola** [bcc-code/bccm-player#27]
Is pinch to zoom is available for video

**Comment by andreasgangso** [comment]
Not available at the moment but I agree that can be added to the default controls.
Should be fairly simple to implement with InteractiveViewer, similar to chewie.

I'd be happy to review a PR for this.

**Comment by sudhanshugairola** [comment]
InteractiveViewer is not a good approach for maintaining height and width

**Comment by sudhanshugairola** [comment]
may be that need 
`int width;
int height;
int rotationDegrees;
if (exoPlayer.getVideoFormat() != null) {
        Format videoFormat = exoPlayer.getVideoFormat();
        width = videoFormat.width;
        height = videoFormat.height;
        rotationDegrees = videoFormat.rotationDegrees;
        // Switch the width/height if video was taken in portrait mode
        if (rotationDegrees == 90 || rotationDegrees == 270) {
          width = exoPlayer.getVideoFormat().height;
          height = exoPlayer.getVideoFormat().width;
        }
        
      }`

**Comment by sudhanshugairola** [comment]
also aspect ratio require of perfect zooming

**Comment by andreasgangso** [comment]
You mean to pinch-zoom so that it fills the screen, right? Good point. 
When this task is picked up, we should look into what apps like Netflix/youtube does and copy that.
If it's just pinch and it zooms to fill the screen, interactiviewer is overkill and so this just depends on #9 and scaling the VideoPlatformView.

**Comment by sudhanshugairola** [comment]
Hmm right, YouTube, Netflix, prime video or other platforms use width and height and aspect ratio of video, through this video details they adjust fill to screen by pinch to zoom
