### ISSUE TITLE
channel-error

### ISSUE THREAD

**Issue by AALAMILLO** [bcc-code/bccm-player#28]
Hi! i try the sample code that is on git hub and have this exception:

code: 'channel-error',
message: 'Unable to establish connection on channel.',

**My code:**

import 'package:flutter/material.dart';
import 'package:bccm_player/bccm_player.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Material App Bar'),
        ),
        body: const Center(
          child: SimplePlayer()
        ),
      ),
    );
  }
}

class SimplePlayer extends StatefulWidget {
  const SimplePlayer({super.key});

  @override
  State<SimplePlayer> createState() => _SimplePlayerState();
}

class _SimplePlayerState extends State<SimplePlayer> {
  late BccmPlayerController playerController;

  @override
  void initState() {
    // You can also use the global "primary" controller: BccmPlayerController.primary;
    // The primary player has superpowers like notification player, background playback, casting, etc.
    playerController = BccmPlayerController(
      MediaItem(
        url: 'https://samplelib.com/lib/preview/mp4/sample-5s.mp4'
      ),
    );
    playerController.initialize().then((_) => playerController.setMixWithOthers(true)); // if you want to play together with other videos
    super.initState();
  }

  @override
  void dispose() {
    playerController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return ListView(
      children: [
        Column(
          children: [
            BccmPlayerView(
              playerController,
              //config: BccmPlayerViewConfig()
            ),
            ElevatedButton(
              onPressed: () {
                playerController.setPrimary();
              },
              child: const Text('Make primary'),
            ),
            ElevatedButton(
              onPressed: () {
                final currentMs = playerController.value.playbackPositionMs;
                if (currentMs != null) {
                  playerController.seekTo(Duration(milliseconds: currentMs + 20000));
                }
              },
              child: const Text('Skip 20 seconds'),
            ),
          ],
        ),
      ],
    );
  }
}

**Sdkversion**
minSdkVersion 21

**Manifest**
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <uses-permission android:name="android.permission.INTERNET" />
    <application
        android:label="sample2"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:supportsPictureInPicture="true"

any idea?

**Comment by andreasgangso** [comment]
Hi.
This is probably 1 of 2 things:

  1.  The plugins native side hasnt been built. Did you remember to restart your app completely? Hot reload is not enough.
  2.  The plugin crashed on startup. Check the debug logs for any exceptions preceding the "channel" errors. If there are none, open Android studio or xcode and run the project from there, as those give more logs than e.g. visual studio code. Post the logs here.

Let me know how it goes!

________________________________
Fra: AALAMILLO ***@***.***>
Sendt: lørdag, august 19, 2023 4:49 am
Til: bcc-code/bccm-player ***@***.***>
Kopi: Subscribed ***@***.***>
Emne: [bcc-code/bccm-player] channel-error (Issue #28)


Hi! i try the sample code that is on git hub and have this exception:

code: 'channel-error',
message: 'Unable to establish connection on channel.',

My code:

import 'package:flutter/material.dart';
import 'package:bccm_player/bccm_player.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
const MyApp({super.key});

@OverRide<https://github.com/OverRide>
Widget build(BuildContext context) {
return MaterialApp(
title: 'Material App',
home: Scaffold(
appBar: AppBar(
title: const Text('Material App Bar'),
),
body: const Center(
child: SimplePlayer()
),
),
);
}
}

class SimplePlayer extends StatefulWidget {
const SimplePlayer({super.key});

@OverRide<https://github.com/OverRide>
State createState() => _SimplePlayerState();
}

class _SimplePlayerState extends State {
late BccmPlayerController playerController;

@OverRide<https://github.com/OverRide>
void initState() {
// You can also use the global "primary" controller: BccmPlayerController.primary;
// The primary player has superpowers like notification player, background playback, casting, etc.
playerController = BccmPlayerController(
MediaItem(
url: 'https://samplelib.com/lib/preview/mp4/sample-5s.mp4'
),
);
playerController.initialize().then((_) => playerController.setMixWithOthers(true)); // if you want to play together with other videos
super.initState();
}

@OverRide<https://github.com/OverRide>
void dispose() {
playerController.dispose();
super.dispose();
}

@OverRide<https://github.com/OverRide>
Widget build(BuildContext context) {
return ListView(
children: [
Column(
children: [
BccmPlayerView(
playerController,
//config: BccmPlayerViewConfig()
),
ElevatedButton(
onPressed: () {
playerController.setPrimary();
},
child: const Text('Make primary'),
),
ElevatedButton(
onPressed: () {
final currentMs = playerController.value.playbackPositionMs;
if (currentMs != null) {
playerController.seekTo(Duration(milliseconds: currentMs + 20000));
}
},
child: const Text('Skip 20 seconds'),
),
],
),
],
);
}
}

Sdkversion
minSdkVersion 21

Manifest



<activity
android:name=".MainActivity"
android:supportsPictureInPicture="true"

any idea?

**Comment by AALAMILLO** [comment]
Hi! Thanks for answer.

1.- Yes, actually i have been deleted the emulator and create again.
2.- Log for Android Studio;

![image](https://github.com/bcc-code/bccm-player/assets/71103258/23ed259b-319f-49f7-a8e6-29f488db5799)

**Comment by andreasgangso** [comment]
Post the logs as text instead of a screenshot, as the important bits seem to be further up.
Preferably add a filter with "package:mine", otherwise its the whole syslog

Sendt fra Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Fra: AALAMILLO ***@***.***>
Sendt: Saturday, August 19, 2023 9:06:41 PM
Til: bcc-code/bccm-player ***@***.***>
Kopi: Andreas Gangsø ***@***.***>; Comment ***@***.***>
Emne: Re: [bcc-code/bccm-player] channel-error (Issue #28)


Hi! Thanks for answer.

1.- Yes, actually i have been deleted the emulator and create again.
2.- Log for Android Studio;

[image]<https://user-images.githubusercontent.com/71103258/261815639-23ed259b-319f-49f7-a8e6-29f488db5799.png>
