### ISSUE TITLE
Feature: disposePlayer()

### ISSUE THREAD

**Issue by andreasgangso** [bcc-code/bccm-player#3]
I never noticed that this was missing because we never needed more than 1 persistent player.

1. Add a disposePlayer(playerId) method in [playback_platform_pigeon.dart (see pigeons readme)](https://github.com/bcc-code/bccm-player/blob/main/pigeons),
2. Run pigeon
3. Implement the generated interface in PlaybackApiImpl on android and iOS
4. Android: Dispose by removing it from the playerControllers array in PlaybackService.kt and calling release() on the playerController.
5: iOS: not sure, but probably just stop it and remove all references so that it gets garbage collected.

**Comment by sudhanshugairola** [comment]
Can you made this easy and simple like other players like video_player or better_player
so other users can customize ui of player according their need like 
1. list of quality, subtitle, audio with selection functions.
2. current status of player and seek progress functions.
3. manual disposing player for list of videos.
4. videoplayervalues like aspect ratios, current timestamp etc

**Comment by sudhanshugairola** [comment]
that important for a open source video player

**Comment by sudhanshugairola** [comment]
@andreasgangso

**Comment by andreasgangso** [comment]
For settings and custom ui, you can do a bunch of this already manually. Look at the default_controls.dart source code in the repo.
But i am going to make it easier to replace default_controls without losing fullscreen functionality.

You can read player state through the plugins StateNotifier (see readme).

For videos in a list etc, that's something which is possible today but it is not optimal.
We are going to work on this in Q3/Q4 2023, most likely.
But for now the plugin is definitely optimized for a VOD type app where you only need 1 powerful "primary" player (see readme about this).

But videos shown as part of a list usually have less requirements (no need for advanced features like pip, chromecast, settings, etc), so video_player would be sufficient. You can use it alongside bccm_player without issues.

________________________________
Fra: Sudhanshu Gairola ***@***.***>
Sendt: lørdag, august 5, 2023 2:40 pm
Til: bcc-code/bccm-player ***@***.***>
Kopi: Andreas Gangsø ***@***.***>; Mention ***@***.***>
Emne: Re: [bcc-code/bccm-player] Feature: disposePlayer() (Issue #3)


@andreasgangso<https://github.com/andreasgangso>

**Comment by andreasgangso** [comment]
This will come as part of https://github.com/bcc-code/bccm-player/pull/10 which I'll probably release within this week.
It's already available as prerelease though, with:
```yml
dependencies:
  bccm_player: ^0.2.3-alpha.1
```

It'll be way more similar to video_player etc, allowing you to do this:

```dart

import 'package:bccm_player/bccm_player.dart';
import 'package:bccm_player_example/example_videos.dart';
import 'package:flutter/material.dart';

class SinglePlayer extends StatefulWidget {
  const SinglePlayer({super.key});

  @override
  State<SinglePlayer> createState() => _SinglePlayerState();
}

class _SinglePlayerState extends State<SinglePlayer> {
  late BccmPlayerController controller;

  @override
  void initState() {
    // For VOD apps just use `BccmPlayerInterface.instance.primaryController`
    controller = BccmPlayerController(
      MediaItem(
        url: 'https://devstreaming-cdn.apple.com/videos/streaming/examples/adv_dv_atmos/main.m3u8',
        mimeType: 'application/x-mpegURL',
        metadata: MediaMetadata(title: 'Apple advanced (HLS/HDR)'),
      ),
    );
    controller.initialize().then((_) => controller.setMixWithOthers(true)); // if you want to play together with other videos
    super.initState();
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return ListView(
      children: [
        Column(
          children: [
            VideoPlayerView(controller: controller),
            ElevatedButton(
              onPressed: () {
                controller.setPrimary();
              },
              child: const Text('Make primary'),
            ),
            ElevatedButton(
              onPressed: () {
                final currentMs = controller.value.playbackPositionMs;
                if (currentMs != null) {
                  controller.seekTo(Duration(milliseconds: currentMs + 20000));
                }
              },
              child: const Text('Skip 20 seconds'),
            ),
          ],
        ),
      ],
    );
  }
}


```

**Comment by sudhanshugairola** [comment]
I see many time users didn't find perfect videoplayer plugin like your, you
just need to made it some easy access feature and customisation like
better_player so your player cover both video_player and betterplayer
missing things.

**Comment by andreasgangso** [comment]
Audio, subtitles and quality selection is already available in the default controls.
From 0.2.3-alpha.1 its also accessible through 'controller.getTracks()’ and ‘controller.setSelectedTrack(type, id)’.

Im still working on documenting and improving the developer experience, then ill promote it.

Thank you for all the feedback, it helps a lot.
________________________________
Fra: Sudhanshu Gairola ***@***.***>
Sendt: Tuesday, August 8, 2023 6:36:08 PM
Til: bcc-code/bccm-player ***@***.***>
Kopi: Andreas Gangsø ***@***.***>; Mention ***@***.***>
Emne: Re: [bcc-code/bccm-player] Feature: disposePlayer() (Issue #3)


I see many time users didn't find perfect videoplayer plugin like your, you
just need to made it some easy access feature and customisation like
better_player so your player cover both video_player and betterplayer
missing things.

**Comment by sudhanshugairola** [comment]
Yeah great

**Comment by sudhanshugairola** [comment]
Controller.play() and pause done ?

**Comment by andreasgangso** [comment]
Yes of course.
All these features have always been there but it was harder to use because you had to use the methods on «BccmPlatformInterface». Example: ‘BccmPlatformInterface.instance.play(playerId);’

So BccmPlayerController is more just a convenient wrapper: ‘controller.play()’ but under the hood its the same.

Sendt fra Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Fra: Sudhanshu Gairola ***@***.***>
Sendt: Tuesday, August 8, 2023 7:28:40 PM
Til: bcc-code/bccm-player ***@***.***>
Kopi: Andreas Gangsø ***@***.***>; Mention ***@***.***>
Emne: Re: [bcc-code/bccm-player] Feature: disposePlayer() (Issue #3)


Controller.play() and pause done ?

**Comment by ThakarRajesh** [comment]
Thank you for creating this excellent video player plugin! We're encountering a couple of issues and would appreciate your assistance.

**Background Video Playback**: When a video fails to load and we navigate back to the previous screen, the video continues to play in the background. Although we call the dispose method on the video player, this issue persists. Is there a way to completely dispose of the video player when returning to the previous screen?

**Preview Video Thumbnail**: The video player sometimes loads the previews video thumbnail instead of the actual video. How can we resolve this issue?

Your help would be highly appreciated. Thank you!

**Comment by andreasgangso** [comment]
> @andreasgangso Thank you for creating this excellent video player plugin! We're encountering a couple of issues and would appreciate your assistance.
> 
> **Background Video Playback**: When a video fails to load and we navigate back to the previous screen, the video continues to play in the background. Although we call the dispose method on the video player, this issue persists. Is there a way to completely dispose of the video player when returning to the previous screen?
> 
> **Preview Video Thumbnail**: The video player everytime loads the previews video thumbnail instead of the actual video. How can we resolve this issue?
> 
> Your help would be highly appreciated. Thank you!

Hi. First, please note that this plugin is no longer properly open source, and the package on pub.dev is very outdated.
Regarding your issues. The first one sounds like the player is the `primary` player, as that's never disposable. https://bcc-code.github.io/bccm-player/advanced-usage/primary-player/
For the second issue, I don't understand what you mean.

**Comment by ThakarRajesh** [comment]
For second issue like
When playing a video (e.g., ABC), if the user navigates back to the preview screen and selects a new video (e.g., XYZ), the thumbnail displayed is still from the previously played video (ABC) instead of the new video (XYZ).

**Comment by andreasgangso** [comment]
> For second issue like When playing a video (e.g., ABC), if the user navigates back to the preview screen and selects a new video (e.g., XYZ), the thumbnail displayed is still from the previously played video (ABC) instead of the new video (XYZ).

Not entirely sure what you mean.
But if you're on android, I think exoplayer also has a bug where the previous mediaitem is still active for the first millisecond. not much you can do about that directly, I think. but you can work around it by adding a delay before showing the player.
You can also try doing stop() before replaceCurrentMediaItem. might help.

**Comment by ThakarRajesh** [comment]
Okay, we will try that.
Is there any workout solution for the first issue to stop playing in background audio?

**Comment by sandipkalola** [comment]
> @andreasgangso Thank you for creating this excellent video player plugin! We're encountering a couple of issues and would appreciate your assistance.
> 
> **Background Video Playback**: When a video fails to load and we navigate back to the previous screen, the video continues to play in the background. Although we call the dispose method on the video player, this issue persists. Is there a way to completely dispose of the video player when returning to the previous screen?
> 
> **Preview Video Thumbnail**: The video player everytime loads the previews video thumbnail instead of the actual video. How can we resolve this issue?
> 
> Your help would be highly appreciated. Thank you!

**Background Video Playback**
-> This issue occure only when you used  **autoplay: true**. You can wait till complete replaceCurrentMediaItem callback. Here is the code link:  [Code Link](https://pastecode.io/s/kvnimw79)

In code load i used bool **isLoadSuccess** variable to load a player once successfully completed call back to resolve your **Previous Video Thumbnail** issue.
