### ISSUE TITLE
ADD support to play video files present in internal storage in android

### ISSUE THREAD

**Issue by PURUSHOTHAM-REDDY-N** [bcc-code/bccm-player#30]
can you add support to play video files present in internal file system of android.

**Comment by sudhanshugairola** [comment]
`controller = BccmPlayerController(
      MediaItem(
        url: /data/user/0/download/',
        mimeType: 'application/x-mpegURL',
        metadata: MediaMetadata(title: 'TEST'),
      ),
    );`

use path provider

**Comment by andreasgangso** [comment]
@sudhanshugairola are you saying this works?

**Comment by sudhanshugairola** [comment]
But video is playing yet

**Comment by PURUSHOTHAM-REDDY-N** [comment]
is there any way that we can have all the controls ?

**Comment by andreasgangso** [comment]
Hi @sudhanshugairola @PURUSHOTHAM-REDDY-N 
I have just tested playing files from internal storage on android, and it works without issues (play/pause/seek, etc)
I tested both HLS (m3u8) and mp4.

Example for Mp4
```dart
  MediaItem(
    url: 'file:////storage/emulated/0/Download/demo.mp4',
    mimeType: 'video/mp4',
    metadata: MediaMetadata(title: 'Local file (mp4)'),
  ),
```

Example for HLS:
```dart
  MediaItem(
    url: 'file:////storage/emulated/0/Download/hls/main.m3u8',
    mimeType: 'application/x-mpegURL',
    metadata: MediaMetadata(title: 'Local file (HLS)'),
  ),
```

For the URL, you may need to start with "file:///", but it also worked with just "/storage/emulated/0/...".

If this does not work, check these things.
- do you have permission to access the file or similar? Check logs for "file not found" or "permission denied".
- did you use a wrong `mimeType`?
- does your video play using any other player? there might be technical issue with your asset.

If it still does not work, please post your <ins>entire log inside a [collapsable section](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab)</ins>, to help debug this.

In the future we'll make it easier to use files and assets in a cross-platform way.

**Comment by sudhanshugairola** [comment]
Ok I will check once again

**Comment by sudhanshugairola** [comment]
you are right its working now, but issue with subtitle field on m3u8 if there is only one subtitle then it now come in tracksData.textTracks

**Comment by sudhanshugairola** [comment]
in online playing it working well, but that issue i got with internal storage m3u8

**Comment by andreasgangso** [comment]
Please keep your messages in 1, github isn't a chat :)
It's better to edit your original

**Comment by sudhanshugairola** [comment]
ok

**Comment by andreasgangso** [comment]
> you are right its working now, but issue with subtitle field on m3u8 if there is only one subtitle then it now come in tracksData.textTracks

If there's a subtitle track, it makes sense that it shows up in textTracks. I don't understand how this is a problem.

Please keep your messages in 1, github isn't a chat :)
It's better to edit your original.
And don't reply with just "ok", use the emoji button on my message instead :)

**Comment by sudhanshugairola** [comment]
i mean while playing internal m3u8 there is issue with subtitle track. and that m3u8 file has only single tracks like 1 audio, 1 subtitle, 1 quality, it show other well without any issue, but i see missing subtitle in internal storage video play.

**Comment by sudhanshugairola** [comment]
![Screenshot_20230822_164857](https://github.com/bcc-code/bccm-player/assets/42227576/4e206f26-1240-4512-a7ce-eacc845e8a9b)

**Comment by sudhanshugairola** [comment]
if (tracksData != null && tracksData.textTracks.length >= 1) by this i got subtitle, now working well.

**Comment by PURUSHOTHAM-REDDY-N** [comment]
@andreasgangso @sudhanshugairola 
im using local files to play video, it is playing but controls for play , pause and seek bar not working , when i tried to press skip, video is playing from start


this is my implementatioin

import 'dart:async';
import 'package:flutter/material.dart';
import 'dart:io';
import 'package:permission_handler/permission_handler.dart';
import 'package:bccm_player/bccm_player.dart';

class VideoPlayerScreen extends StatefulWidget {
  final String path;

  VideoPlayerScreen({required this.path});

  @override
  _VideoPlayerScreenState createState() => _VideoPlayerScreenState();
}

class _VideoPlayerScreenState extends State<VideoPlayerScreen> {
  late BccmPlayerController playerController;

  @override
  void initState() {
    super.initState();
    _requestPermission();
    playerController = BccmPlayerController.primary(
      MediaItem(
        url: 'file:////${widget.path}',
        mimeType: 'video/mp4',
        metadata: MediaMetadata(title: 'Apple advanced (HLS/HDR)'),
      ),
    );
    playerController.initialize().then((_) => playerController.setMixWithOthers(
        true)); // if you want to play together with other videos
    super.initState();
  }

  @override
  void dispose() {
    if (!playerController.isPrimary) {
      playerController.dispose();
    }
    super.dispose();
  }

  Future<void> _requestPermission() async {
    // Requesting the storage permission
    final status = await Permission.storage.request();

    if (status.isGranted) {
    } else if (status.isDenied) {}
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Video Player'),
      ),
      body: BccmPlayerView(
        config: BccmPlayerViewConfig(
            allowSystemGestures: false, useSurfaceView: true),
        playerController,
        //config: BccmPlayerViewConfig()
      ),
    );
  }
}

**Comment by sudhanshugairola** [comment]
bccm_player: ^1.1.1

Use latest version

**Comment by PURUSHOTHAM-REDDY-N** [comment]
@sudhanshugairola i did flutter clean and  im using the latest version bccm_player: ^1.1.1  im still getting this issue

**Comment by sudhanshugairola** [comment]
That problem is only with old version. I also check it work fine with new version.

**Comment by PURUSHOTHAM-REDDY-N** [comment]
@sudhanshugairola  can you share your configuration code , i will cross check with mine , im using the latest version of this package still im getting this issue

**Comment by sudhanshugairola** [comment]
Sure wait first I will check your code once

**Comment by PURUSHOTHAM-REDDY-N** [comment]
@sudhanshugairola check here https://github.com/PURUSHOTHAM-REDDY-N/Flutter-video-player

**Comment by sudhanshugairola** [comment]
Ah great

**Comment by sudhanshugairola** [comment]
`import 'dart:io';
import 'package:bccm_player/bccm_player.dart';
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:bccm_player/src/pigeon/playback_platform_pigeon.g.dart';
import 'package:bccm_player/src/widgets/controls/default/settings_option_list.dart';
import 'package:bccm_player/theme/bccm_player_theme.dart';

import 'package:collection/collection.dart';
import 'package:universal_io/io.dart';

class SinglePlayer extends StatefulWidget {
  const SinglePlayer({key});

  @override
  State<SinglePlayer> createState() => _SinglePlayerState();
}

class _SinglePlayerState extends State<SinglePlayer> {
  late BccmPlayerController controller;

  @override
  void initState() {
    // You can also use the global "primary" controller.
    // The primary player has superpowers like notification player, background playback, casting, etc:
    // final controller = BccmPlayerInterface.instance.primaryController;
    controller = BccmPlayerController(
      MediaItem(
        url: '/data/user/0/com.test.bcc/app_flutter/newtest.m3u8',
        mimeType: 'application/x-mpegURL',
        metadata: MediaMetadata(title: 'TEST'),
      ),
    );
    
    controller.initialize().then((_) => controller.setMixWithOthers(false)); // if you want to play together with other videos
    super.initState();
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final tracksFuture = controller.getTracks();
    return Scaffold(
      appBar: AppBar(
        title: Text("new")
      ),
      backgroundColor: Colors.black,
      body:ListView(
      children: [
        Column(
          children: [
            BccmPlayerView(
              controller,
              //config: BccmPlayerViewConfig()
            ),
            ElevatedButton(
              onPressed: () {
                final currentMs = controller.value.playbackPositionMs;
                if (currentMs != null) {
                  controller.seekTo(Duration(milliseconds: currentMs + 20000));
                }
              },
              child: const Text('Skip 20 seconds'),
            ),
            ElevatedButton(
              onPressed: () {
                print(controller.value.playbackState);
                final currentMs = controller.value.playbackPositionMs;
                if (currentMs != null) {
                  if(controller.value.playbackState == PlaybackState.playing){
                    controller.pause();
                  }
                  else{
                    controller.play();
                  }
                }
              },
              child: const Text('Play'),
            ),
            ElevatedButton(
              onPressed: () {
                controller.enterNativeFullscreen();
              },
              child: const Text('Full screen'),
            ),
            ElevatedButton(
              onPressed: () {
                // print("asssss ${controller.value.}");
                // controller.dispose();
              },
              child: const Text('Exit Player'),
            ),
          ],
        ),
      ],
      ),
    );
  }
}`

**Comment by sudhanshugairola** [comment]
```
import 'dart:io';
import 'package:bccm_player/bccm_player.dart';
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:bccm_player/src/pigeon/playback_platform_pigeon.g.dart';
import 'package:bccm_player/src/widgets/controls/default/settings_option_list.dart';
import 'package:bccm_player/theme/bccm_player_theme.dart';

import 'package:collection/collection.dart';
import 'package:universal_io/io.dart';

class SinglePlayer extends StatefulWidget {
  const SinglePlayer({key});

  @override
  State<SinglePlayer> createState() => _SinglePlayerState();
}

class _SinglePlayerState extends State<SinglePlayer> {
  late BccmPlayerController controller;

  @override
  void initState() {
    // You can also use the global "primary" controller.
    // The primary player has superpowers like notification player, background playback, casting, etc:
    // final controller = BccmPlayerInterface.instance.primaryController;
    controller = BccmPlayerController(
      MediaItem(
        url: '/data/user/0/com.test.bcc/app_flutter/newtest.m3u8',
        mimeType: 'application/x-mpegURL',
        metadata: MediaMetadata(title: 'TEST'),
      ),
    );
    
    controller.initialize().then((_) => controller.setMixWithOthers(false)); // if you want to play together with other videos
    super.initState();
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final tracksFuture = controller.getTracks();
    return Scaffold(
      appBar: AppBar(
        title: Text("new")
      ),
      backgroundColor: Colors.black,
      body:ListView(
      children: [
        Column(
          children: [
            BccmPlayerView(
              controller,
              //config: BccmPlayerViewConfig()
            ),
            ElevatedButton(
              onPressed: () {
                final currentMs = controller.value.playbackPositionMs;
                if (currentMs != null) {
                  controller.seekTo(Duration(milliseconds: currentMs + 20000));
                }
              },
              child: const Text('Skip 20 seconds'),
            ),
            ElevatedButton(
              onPressed: () {
                print(controller.value.playbackState);
                final currentMs = controller.value.playbackPositionMs;
                if (currentMs != null) {
                  if(controller.value.playbackState == PlaybackState.playing){
                    controller.pause();
                  }
                  else{
                    controller.play();
                  }
                }
              },
              child: const Text('Play'),
            ),
            ElevatedButton(
              onPressed: () {
                controller.enterNativeFullscreen();
              },
              child: const Text('Full screen'),
            ),
            ElevatedButton(
              onPressed: () {
                // print("asssss ${controller.value.}");
                // controller.dispose();
              },
              child: const Text('Exit Player'),
            ),
          ],
        ),
      ],
      ),
    );
  }
}
```import 'dart:io';
import 'package:bccm_player/bccm_player.dart';
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:bccm_player/src/pigeon/playback_platform_pigeon.g.dart';
import 'package:bccm_player/src/widgets/controls/default/settings_option_list.dart';
import 'package:bccm_player/theme/bccm_player_theme.dart';

import 'package:collection/collection.dart';
import 'package:universal_io/io.dart';

class SinglePlayer extends StatefulWidget {
  const SinglePlayer({key});

  @override
  State<SinglePlayer> createState() => _SinglePlayerState();
}

class _SinglePlayerState extends State<SinglePlayer> {
  late BccmPlayerController controller;

  @override
  void initState() {
    // You can also use the global "primary" controller.
    // The primary player has superpowers like notification player, background playback, casting, etc:
    // final controller = BccmPlayerInterface.instance.primaryController;
    controller = BccmPlayerController(
      MediaItem(
        url: '/data/user/0/com.test.bcc/app_flutter/newtest.m3u8',
        mimeType: 'application/x-mpegURL',
        metadata: MediaMetadata(title: 'TEST'),
      ),
    );
    
    controller.initialize().then((_) => controller.setMixWithOthers(false)); // if you want to play together with other videos
    super.initState();
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final tracksFuture = controller.getTracks();
    return Scaffold(
      appBar: AppBar(
        title: Text("new")
      ),
      backgroundColor: Colors.black,
      body:ListView(
      children: [
        Column(
          children: [
            BccmPlayerView(
              controller,
              //config: BccmPlayerViewConfig()
            ),
            ElevatedButton(
              onPressed: () {
                final currentMs = controller.value.playbackPositionMs;
                if (currentMs != null) {
                  controller.seekTo(Duration(milliseconds: currentMs + 20000));
                }
              },
              child: const Text('Skip 20 seconds'),
            ),
            ElevatedButton(
              onPressed: () {
                print(controller.value.playbackState);
                final currentMs = controller.value.playbackPositionMs;
                if (currentMs != null) {
                  if(controller.value.playbackState == PlaybackState.playing){
                    controller.pause();
                  }
                  else{
                    controller.play();
                  }
                }
              },
              child: const Text('Play'),
            ),
            ElevatedButton(
              onPressed: () {
                controller.enterNativeFullscreen();
              },
              child: const Text('Full screen'),
            ),
            ElevatedButton(
              onPressed: () {
                // print("asssss ${controller.value.}");
                // controller.dispose();
              },
              child: const Text('Exit Player'),
            ),
          ],
        ),
      ],
      ),
    );
  }
}

**Comment by sudhanshugairola** [comment]
```
import 'dart:io';
import 'package:bccm_player/bccm_player.dart';
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:bccm_player/src/pigeon/playback_platform_pigeon.g.dart';
import 'package:bccm_player/src/widgets/controls/default/settings_option_list.dart';
import 'package:bccm_player/theme/bccm_player_theme.dart';

import 'package:collection/collection.dart';
import 'package:universal_io/io.dart';

class SinglePlayer extends StatefulWidget {
  const SinglePlayer({key});

  @override
  State<SinglePlayer> createState() => _SinglePlayerState();
}

class _SinglePlayerState extends State<SinglePlayer> {
  late BccmPlayerController controller;

  @override
  void initState() {
    // You can also use the global "primary" controller.
    // The primary player has superpowers like notification player, background playback, casting, etc:
    // final controller = BccmPlayerInterface.instance.primaryController;
    controller = BccmPlayerController(
      MediaItem(
        url: '/data/user/0/com.test.bcc/app_flutter/newtest.m3u8',
        mimeType: 'application/x-mpegURL',
        metadata: MediaMetadata(title: 'TEST'),
      ),
    );
    
    controller.initialize().then((_) => controller.setMixWithOthers(false)); // if you want to play together with other videos
    super.initState();
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final tracksFuture = controller.getTracks();
    return Scaffold(
      appBar: AppBar(
        title: Text("new")
      ),
      backgroundColor: Colors.black,
      body:ListView(
      children: [
        Column(
          children: [
            BccmPlayerView(
              controller,
              //config: BccmPlayerViewConfig()
            ),
            ElevatedButton(
              onPressed: () {
                final currentMs = controller.value.playbackPositionMs;
                if (currentMs != null) {
                  controller.seekTo(Duration(milliseconds: currentMs + 20000));
                }
              },
              child: const Text('Skip 20 seconds'),
            ),
            ElevatedButton(
              onPressed: () {
                print(controller.value.playbackState);
                final currentMs = controller.value.playbackPositionMs;
                if (currentMs != null) {
                  if(controller.value.playbackState == PlaybackState.playing){
                    controller.pause();
                  }
                  else{
                    controller.play();
                  }
                }
              },
              child: const Text('Play'),
            ),
            ElevatedButton(
              onPressed: () {
                controller.enterNativeFullscreen();
              },
              child: const Text('Full screen'),
            ),
            ElevatedButton(
              onPressed: () {
                // print("asssss ${controller.value.}");
                // controller.dispose();
              },
              child: const Text('Exit Player'),
            ),
          ],
        ),
      ],
      ),
    );
  }
}
```

**Comment by PURUSHOTHAM-REDDY-N** [comment]
@sudhanshugairola controls are working only when i click on full screen button

**Comment by sudhanshugairola** [comment]
You mean native controls?

**Comment by PURUSHOTHAM-REDDY-N** [comment]
yes

**Comment by PURUSHOTHAM-REDDY-N** [comment]
@sudhanshugairola  there any method to initialize player default with NativeFullscreen

**Comment by sudhanshugairola** [comment]
ok you want full screen with native controls, as you reach to videoplayer page?

**Comment by PURUSHOTHAM-REDDY-N** [comment]
yes

**Comment by sudhanshugairola** [comment]
```
import 'dart:io';
import 'package:auto_orientation/auto_orientation.dart';
import 'package:bccm_player/bccm_player.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:bccm_player/src/pigeon/playback_platform_pigeon.g.dart';
import 'package:bccm_player/src/widgets/controls/default/settings_option_list.dart';
import 'package:bccm_player/theme/bccm_player_theme.dart';

import 'package:collection/collection.dart';
import 'package:universal_io/io.dart';
import 'package:wakelock_plus/wakelock_plus.dart';

class SinglePlayer extends StatefulWidget {
  const SinglePlayer({key});

  @override
  State<SinglePlayer> createState() => _SinglePlayerState();
}

class _SinglePlayerState extends State<SinglePlayer> {
  BccmPlayerController? controller;

  @override
  void initState() {
    WakelockPlus.enable();
    AutoOrientation.landscapeAutoMode(forceSensor: true);
    SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: []);
    controller = BccmPlayerController(
      MediaItem(
        url: 'you path',
        mimeType: 'application/x-mpegURL',
        metadata: MediaMetadata(title: 'Apple advanced (HLS/HDR)'),
      ),
    );
    controller!.initialize().then((_){
      controller!.setMixWithOthers(true);
    }); // if you want to play together with other videos
    super.initState();
  }


  @override
  void dispose() {
    AutoOrientation.portraitAutoMode();
    SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual,
        overlays: SystemUiOverlay.values);
    controller!.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      body:Container(
        width: controller?.value.videoSize?.width.roundToDouble() ?? MediaQuery.of(context).size.width,
        height: controller?.value.videoSize?.height.roundToDouble() ?? MediaQuery.of(context).size.height,
        child: VideoPlatformView(
          playerController: controller!, showControls: true,
          allowSystemGestures: true,
          //config: BccmPlayerViewConfig()
        ),
      )
    );
  }
}
```

**Comment by sudhanshugairola** [comment]
import 'dart:io';
import 'package:auto_orientation/auto_orientation.dart';
import 'package:bccm_player/bccm_player.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:bccm_player/src/pigeon/playback_platform_pigeon.g.dart';
import 'package:bccm_player/src/widgets/controls/default/settings_option_list.dart';
import 'package:bccm_player/theme/bccm_player_theme.dart';

import 'package:collection/collection.dart';
import 'package:universal_io/io.dart';
import 'package:wakelock_plus/wakelock_plus.dart';

class SinglePlayer extends StatefulWidget {
  const SinglePlayer({key});

  @override
  State<SinglePlayer> createState() => _SinglePlayerState();
}

class _SinglePlayerState extends State<SinglePlayer> {
  BccmPlayerController? controller;

  @override
  void initState() {
    WakelockPlus.enable();
    AutoOrientation.landscapeAutoMode(forceSensor: true);
    SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: []);
    controller = BccmPlayerController(
      MediaItem(
        url: 'your path',
        mimeType: 'application/x-mpegURL',
        metadata: MediaMetadata(title: 'Apple advanced (HLS/HDR)'),
      ),
    );
    controller!.initialize().then((_){
      controller!.setMixWithOthers(true);
    }); // if you want to play together with other videos
    super.initState();
  }


  @override
  void dispose() {
    AutoOrientation.portraitAutoMode();
    SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual,
        overlays: SystemUiOverlay.values);
    controller!.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      body:Container(
        width: controller?.value.videoSize?.width.roundToDouble() ?? MediaQuery.of(context).size.width,
        height: controller?.value.videoSize?.height.roundToDouble() ?? MediaQuery.of(context).size.height,
        child: BccmPlayerView(
          controller!,
          config: BccmPlayerViewConfig(
            useSurfaceView: false,
              allowSystemGestures: true,
          )
        ),
      )
    );
  }
}

**Comment by sudhanshugairola** [comment]
Custom controls also work on my side with internal storage media files.

```
import 'dart:io';
import 'package:auto_orientation/auto_orientation.dart';
import 'package:bccm_player/bccm_player.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:bccm_player/src/pigeon/playback_platform_pigeon.g.dart';
import 'package:bccm_player/src/widgets/controls/default/settings_option_list.dart';
import 'package:bccm_player/theme/bccm_player_theme.dart';

import 'package:collection/collection.dart';
import 'package:universal_io/io.dart';
import 'package:wakelock_plus/wakelock_plus.dart';

class SinglePlayer extends StatefulWidget {
  const SinglePlayer({key});

  @override
  State<SinglePlayer> createState() => _SinglePlayerState();
}

class _SinglePlayerState extends State<SinglePlayer> {
  BccmPlayerController? controller;

  @override
  void initState() {
    WakelockPlus.enable();
    AutoOrientation.landscapeAutoMode(forceSensor: true);
    SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual, overlays: []);
    controller = BccmPlayerController(
      MediaItem(
        url: 'file://///data/user/0/com.gairola.StreamFlix/app_flutter/download/You/S2 E1 A Fresh Start.m3u8',
        mimeType: 'application/x-mpegURL',
        metadata: MediaMetadata(title: 'Apple advanced (HLS/HDR)'),
      ),
    );
    controller!.initialize().then((_){
      controller!.setMixWithOthers(true);
    }); // if you want to play together with other videos
    super.initState();
  }


  @override
  void dispose() {
    AutoOrientation.portraitAutoMode();
    SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual,
        overlays: SystemUiOverlay.values);
    controller!.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      body:Container(
        width: controller?.value.videoSize?.width.roundToDouble() ?? MediaQuery.of(context).size.width,
        height: controller?.value.videoSize?.height.roundToDouble() ?? MediaQuery.of(context).size.height,
        child: BccmPlayerView(
          controller!,
          config: BccmPlayerViewConfig(
            useSurfaceView: false,
              allowSystemGestures: true,
          )
        ),
      )
    );
  }
}
```

**Comment by andreasgangso** [comment]
Hi, I actually accidently removed the possibility to have native controls as part of a major refactor in v1.0.0+. I'll make sure to add it back in the next release

**Comment by PURUSHOTHAM-REDDY-N** [comment]
ohh ok i wil be waiting for your next release thank you. @andreasgangso

**Comment by andreasgangso** [comment]
@PURUSHOTHAM-REDDY-N 
Actually I was wrong. It's still very possible in the current versions, no update needed:

```dart
VideoPlatformView(
  playerController: BccmPlayerController.primary,
  showControls: true,
),
```

**Comment by PURUSHOTHAM-REDDY-N** [comment]
@andreasgangso  controls are working fine now

but when i first time open app and open a video its is showing controls but video is not playing 
after that when i tried to play another video it is playing perfectly

here is  my code 

import 'dart:async';
import 'package:flutter/material.dart';
import 'package:bccm_player/bccm_player.dart';

class VideoPlayerScreen extends StatefulWidget {
  final String path;

  VideoPlayerScreen({required this.path});

  @override
  _VideoPlayerScreenState createState() => _VideoPlayerScreenState();
}

class _VideoPlayerScreenState extends State<VideoPlayerScreen> {
  @override
  void initState() {
    BccmPlayerController.primary.initialize();
    BccmPlayerController.primary.replaceCurrentMediaItem(
        MediaItem(
          url: widget.path,
          mimeType: 'video/*',
          metadata: MediaMetadata(title: 'TEST'),
        ),
        autoplay: true);

    super.initState();
  }

  @override
  void dispose() {
    BccmPlayerController.primary.pause();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("new")),
      backgroundColor: Colors.black,
      body: ListView(
        children: [
          Center(
            child: Column(
              children: [
                VideoPlatformView(
                  playerController: BccmPlayerController.primary,
                  showControls: true,
                ),
                ElevatedButton(
                    onPressed: () =>
                        BccmPlayerController.primary.enterNativeFullscreen(),
                    child: Text("enter"))
              ],
            ),
          ),
        ],
      ),
    );
  }
}

**Comment by andreasgangso** [comment]
@PURUSHOTHAM-REDDY-N 
I'm not sure what could be wrong with your code, but it might be a race condition with initialization.
Try making your main async, and call `await BccmPlayerInterface.instance.setup();`.
Let me know if it worked or not:

```dart
Future main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await BccmPlayerInterface.instance.setup();
  runApp(const MyApp());
}
```

Tip: Put your code inside triple-` to format your code like this^ in a comment, see https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting.

**Comment by PURUSHOTHAM-REDDY-N** [comment]
@andreasgangso  it worked ! thank you, but when i tried to play the video controls are not visible if i make the video full screen then the controls are showing it is happening for some files only 

and is there any way that we can play the video in full screen by default

this is my repo
https://github.com/PURUSHOTHAM-REDDY-N/Flutter-video-player

check this once
https://github.com/bcc-code/bccm-player/assets/84611950/0d93b839-6d9d-4d12-a6af-093204d15b77
