### ISSUE TITLE
Flutter Web Implementation

### ISSUE THREAD

**Issue by jsaulsberry-cvet** [bcc-code/bccm-player#31]
This app says that is compatible with flutter web. These javascript functions are referenced. 
<img width="1256" alt="Screenshot 2023-08-19 at 11 36 01 PM" src="https://github.com/bcc-code/bccm-player/assets/72142765/b37687e8-ba70-4f16-ad9f-39a100b02080">

but there are no cdn links provided in the documentation get access to these functions. Also these javascript files are not referenced in the example package.

Therefore this fails on flutter web

**Comment by andreasgangso** [comment]
You're right, it's wrong to show web as supported because it's not.
I've removed "web" from the pubspec so that it doesn't show up as supported starting with the next release 👍
