### ISSUE TITLE
Bug: Tries to play HDR on unsupported device

### ISSUE THREAD

**Issue by sudhanshugairola** [bcc-code/bccm-player#35]
Player automatically play HDR video on unsupported low end device that cause color wash out, that well if it play HDR or dolby vision on supported device only, otherwise play SDR resolution

**Comment by sudhanshugairola** [comment]
check on this url: https://devstreaming-cdn.apple.com/videos/streaming/examples/adv_dv_atmos/main.m3u8

**Comment by andreasgangso** [comment]
Thank you for reporting this. Do you want to try fixing it @sudhanshugairola?

**Comment by sudhanshugairola** [comment]
I don't know how to did this !

**Comment by sudhanshugairola** [comment]
any update on this bug?

**Comment by andreasgangso** [comment]
No, this is not going to be a priority unfortunately.

By the way, can you verify if I have understood you correctly?:
- Use a device which does not support HDR
- Play an HLS stream with both HDR and SDR content

Wanted/expected: The player selects an SDR stream
What actually happens: The player selects an HDR stream

**Comment by sudhanshugairola** [comment]
Yes I check player select high bitrate resolution and select HDR because HDR is high high bitrate. If a SDR is has more bitrate than HDR resolution then it select SDR first automatically. I think main issue is exoplayer select most high bitrate resolution first.

**Comment by andreasgangso** [comment]
Is this really a problem though, if it plays fine then it's ok?

**Comment by sudhanshugairola** [comment]
Yes problem for those device which not supported HDR,  there it show color washout issue

**Comment by sudhanshugairola** [comment]
https://stackoverflow.com/questions/76465380/is-there-a-way-to-detect-if-exoplayer-is-currently-playing-a-video-with-hdr
