### ISSUE TITLE
Controls not working

### ISSUE THREAD

**Issue by armanhadifatah** [bcc-code/bccm-player#42]
Currently i'm testing this package it works but the controls are not working the video play then when press pause it will not and slider also not moving the time remain 0 while video is playing , my configuration is just the one in the example provided

**Comment by sudhanshugairola** [comment]
simple Use controller.addlistner

**Comment by Joseph-Nathan** [comment]
any news ?

**Comment by sudhanshugairola** [comment]
add in main file

await BccmPlayerInterface.instance.setup();

**Comment by andreasgangso** [comment]
If you get these kinds of issues, what Sudhanshu wrote here should work.
Add `await BccmPlayerInterface.instance.setup();` inside your main.

See docs: https://bcc-code.github.io/bccm-player/usage/
