### ISSUE TITLE
video controls are not showing for some videos

### ISSUE THREAD

**Issue by PURUSHOTHAM-REDDY-N** [bcc-code/bccm-player#43]
when i tried to play the video controls are not visible if i make the video full screen then the controls are showing it is happening for some files only

and is there any way that we can play the video in full screen by default

this is my repo
https://github.com/PURUSHOTHAM-REDDY-N/Flutter-video-player

check this once
https://github.com/bcc-code/bccm-player/assets/84611950/0d93b839-6d9d-4d12-a6af-093204d15b77

**Comment by sudhanshugairola** [comment]
For specific file or every.

**Comment by PURUSHOTHAM-REDDY-N** [comment]
for some files olnly see the video link that i attached @sudhanshugairola 

is there any way that we can  play the video in full screen by default

**Comment by sudhanshugairola** [comment]
May be that video codecs not supported in your phone
