### ISSUE TITLE
Custom Bottom sheet 

### ISSUE THREAD

**Issue by ineffablesam** [bcc-code/bccm-player#47]
Can i have any work around to implement custom bottom sheet?
so i could use packages such as modal_bottom_sheet and implement my own logics
such as open in External apps and custom ui

![Screenshot_1694574078](https://github.com/bcc-code/bccm-player/assets/72622345/2605fa54-a32d-461d-888c-8c190686b9a3)

**Comment by andreasgangso** [comment]
you can build a custom settings ui if you want to.
see controls configs custombuilder
