### ISSUE TITLE
layout controls not worked well ,

### ISSUE THREAD

**Issue by Joseph-Nathan** [bcc-code/bccm-player#48]
i tried example , the hls file loaded well ,
 but , play/pause button not do any thing ,
progress bar not update  ,
video duration not changed ,
forward run backward event ,
on FullScreen player change his dir to .rtl because my app is rtl lang ,
can we controll it or set it permanent

**Comment by sudhanshugairola** [comment]
add in main file

await BccmPlayerInterface.instance.setup();

**Comment by Joseph-Nathan** [comment]
@sudhanshugairola  thanks controls work fine now ,
but FullScreen mode work Horrible ، because my app local textDirection is rtl ,
can i set it permanent to textDirection.ltr ;
