### ISSUE TITLE
Issue with DownloaderListenerPigeon

### ISSUE THREAD

**Issue by sudhanshugairola** [bcc-code/bccm-player#54]
That break downloading progress completely.
Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: dev.flutter.pigeon.bccm_player.DownloaderListenerPigeon.onDownloadStatusChanged. Response ID: 2978

**Comment by andreasgangso** [comment]
Sounds like some outdated dependencies or similar. Try `flutter clean` and rebuilding.
