### ISSUE TITLE
Video quality changing issue on iOS

### ISSUE THREAD

**Issue by hainguyen210** [bcc-code/bccm-player#56]
When I change video quality nothing happens, and it feels like it just changes quality after I reload my app. This happens in both my project and the example on iOs device, everything works fine on Android though.

**Comment by andreasgangso** [comment]
The ios quality setting is more a "max quality" setting. Internally it just sets [preferredPeakBitRate](https://developer.apple.com/documentation/avfoundation/avplayeritem/1388541-preferredpeakbitrate)

**Comment by hainguyen210** [comment]
Oh, that means I can't set a specific resolution individually and have to try another way, right? Thanks for having a look

**Comment by andreasgangso** [comment]
Yup
