### ISSUE TITLE
Player loses state after stopping Chromecast casting

### ISSUE THREAD

**Issue by TamasBarta** [bcc-code/bccm-player#57]
Hi, I ran into issues with Chromecast, namely when I stop casting, the player is in a state, where it can't do anything. (Play button doesn't work, no native notification about player state, 00:00 / 00:00 for length and position, etc) Video also doesn't stop on the Chromecast after stopping in-app. (I could only test on iOS for now, but I can dive in it on Android too, if needed)

I checked [architecture.md](../blob/main/doc/contributing/architecture.md), and the `On session stop` section left me confused. It mentions `unclaimPrimary`, but I couldn't find anything called `unclaimPrimary` in the repo. The only mention seems to be in this doc. I also don't understand what a "episode page" is.

Now I believe this may be the aftermath of a refactor that left the codebase without these parts, but this documentation suggests me that stopping casting and returning to in-app player is not yet supported with Chromecast. Is this the case? Do you have something in mind what it would take to implement for this to work? I don't have experience with neither Chromecast nor the native players, but if you can explain something straightforward, I'm happy to look things up, jump in, and work on this.

Thanks in advance!

**Comment by sudhanshugairola** [comment]
can you please @andreasgangso  casting Docs?

**Comment by sudhanshugairola** [comment]
W/MediaControlChannel(24918): received unexpected error: Invalid Request.
W/MediaControlChannel(24918): received unexpected error: Invalid Request.
W/MediaControlChannel(24918): received unexpected error: Invalid Request.
W/MediaQueue(24918): Error fetching queue item ids, statusCode=2001, statusMessage=null
D/bccm    (24918): playbackState: 1
I/flutter (24918): player replace
I/flutter (24918): Warning: Tried to initialize an initialized player
D/bccm    (24918): playbackState: 2
I/flutter (24918): player replace
I/flutter (24918): Warning: Tried to initialize an initialized player
I/MediaNotificationService(24918): actionsProvider == null
I/DynamiteModule(24918): Considering local module com.google.android.gms.cast.framework.dynamite:0 and remote module com.google.android.gms.cast.framework.dynamite:234955000
I/DynamiteModule(24918): Selected remote version of com.google.android.gms.cast.framework.dynamite, version >= 234955000
V/DynamiteModule(24918): Dynamite loader version >= 2, using loadModule2NoCrashUtils
I/CastDynamiteModuleImpl(24918): anh created by ClassLoader dalvik.system.DelegateLastClassLoader[DexPathList[[zip file "/data/app/~~-cszvrXh4h_4z4Tq9h5cRA==/com.google.android.gms-It9A5xkFgeRIu8m3jgmWtw==/split_DynamiteModulesC.apk"],nativeLibraryDirectories=[/data/app/~~-cszvrXh4h_4z4Tq9h5cRA==/com.google.android.gms-It9A5xkFgeRIu8m3jgmWtw==/split_DynamiteModulesC.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]].
I/HandWritingStubImpl(24918): isKeyboardTypeChanged: false
I/HandWritingStubImpl(24918): refreshLastKeyboardType: 1
I/HandWritingStubImpl(24918): getCurrentKeyboardType: 1
E/FrameEvents(24918): updateAcquireFence: Did not find frame.
E/FrameEvents(24918): updateAcquireFence: Did not find frame.

**Comment by sudhanshugairola** [comment]
Any solution @andreasgangso

**Comment by andreasgangso** [comment]
This is a bit imperfect right now and it would be best to properly transfer the state from the cast media item to AVPlayer/Exoplayer.

However, you can still achieve this with some manual work on the flutter side, as the chromecast events are exposed via `BccmPlayerInterface.instance.chromecastEventStream`. Or `chromecastEventStreamProvider` if you use riverpod.

In our app we listen to CastSessionUnavailable on our "episode page", and simply play that episode when you disconnect.

```
final subscription = BccmPlayerInterface.instance.chromecastEventStream.on<CastSessionUnavailable>().listen((event) {
        // Do something, e.g. BccmPlayerController.primary.replaceCurrentMediaItem().
        // The event here has `playbackPositionMs` which is the last known position on the chromecast.
      });
```

**Comment by andreasgangso** [comment]
Btw the docs was wrong. its `unclaimIfPrimary` so no wonder you didnt find it.

**Comment by TamasBarta** [comment]
@andreasgangso, I finally got the time to try your suggestions, and works well. Thank you!
