### ISSUE TITLE
How to listen to completion of playback?

### ISSUE THREAD

**Issue by TamasBarta** [bcc-code/bccm-player#58]
I'm looking at `BccmPlayerController` in my IDE, and I don't see a way to check if playback of the current item is completed. Is this supported? If not, how do I implement a playlist, that executes arbitrary code between playback of items? My usecase is that I have a playlist, and I want to save progress when playback completes, and progress to the next item.

The closest I see is `.playbackState`, but that only tells, if it is stopped, or playing. I'm afraid that if I check for `== PlaybackState.stopped`, I won't know the reason for being stopped (if it's stopped because it finished, or some other reason).

**Edit:** I tried logging `.playbackState`, and I couldn't even get it to be stopped. It is paused after playback finished.

**Comment by andreasgangso** [comment]
See `player.events`. Example:

```dart
endedSubscription = player.events.where((event) => event is PlaybackEndedEvent).cast<PlaybackEndedEvent>().listen(onPlaybackEnded);
```

remember to dispose the subscription.

**Comment by TamasBarta** [comment]
Thanks! I've tried it, and works well! :) Much appreciated!
