### ISSUE TITLE
How to use with macOS

### ISSUE THREAD

**Issue by gnattu** [bcc-code/bccm-player#62]
I tried to use this for macOS but got the channel error:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      PlaybackPlatformPigeon.attach (package:bccm_player/src/pigeon/playback_platform_pigeon.g.dart:779:7)
<asynchronous suspension>
#1      BccmPlayerNative._setup (package:bccm_player/bccm_player_native.dart:60:5)
<asynchronous suspension>
#2      main (package:bccm_player_example/main.dart:15:3)
<asynchronous suspension>
```

Anything need to modify to make it run with macOS natively? Most APIs should already be the same AFAIK, but there might be slight differences.

**Comment by andreasgangso** [comment]
yea would need some changes to even try macos. Right now we only have an "ios" folder, but we would need to rename that to "darwin" and add `sharedDarwinSource`: https://docs.flutter.dev/packages-and-plugins/developing-packages#shared-ios-and-macos-implementations

but i have no idea if it would work or not

**Comment by gnattu** [comment]
After initial experimentation, it will need some more work, and unfortunately, the API cannot be shared easily.

Firstly, the Google Cast SDK does not support macOS, so functionalities related to it need to be removed from macOS sources.

Secondly, macOS needs to use AppKit, which means the current UIKit views need to be re-implemented. Additionally, APIs like `AVPlayerViewController` need to be replaced by `AVPlayerView` on macOS. Apple's official solution to support these without code change is to use the Mac Catalyst target, but Flutter does not support it (https://github.com/flutter/flutter/issues/33860).

So unfortunately, it is not trivial to run this on macOS natively yet.
