### ISSUE TITLE
Feature: dynamic aspect ratio

### ISSUE THREAD

**Issue by andreasgangso** [bcc-code/bccm-player#9]
The plugin currently assumes 16:9 in many places.
Make this dynamic, so it automatically sizes the VideoPlatformView and controls based on the video aspect ratio.

**Comment by sudhanshugairola** [comment]
When this issue and other will resolve

**Comment by andreasgangso** [comment]
> When this issue and other will resolve

This one is high priority, so it will be done within a few weeks.
The others depend on how we want to prioritize them

**Comment by sudhanshugairola** [comment]
Ok

**Comment by sudhanshugairola** [comment]
Great please also update docs for current video width and height and aspect ratio

**Comment by andreasgangso** [comment]
Released in v1.0.5.
Docs: https://bcc-code.github.io/bccm-player/advanced-usage/player-state/

**Comment by sudhanshugairola** [comment]
Nice
